
import turtle
import time
wn = turtle.Screen()
wn.bgcolor("silver")


t = turtle.Turtle()
t.speed(0)
t.up()
t.goto(-300,-200)
t.down()
t.color("gray")
t.fillcolor("gray")
for i in range(2):
    t.begin_fill()
    t.forward(700)
    t.left(90)
    t.forward(500)
    t.left(90)
    t.end_fill()

t.hideturtle()
t.up()
t.goto(300,150)
t.down()
t.pensize(3)
t.color("black")
t.fillcolor("white")
t.begin_fill()
t.circle(50)
t.end_fill()
t.setheading(90)
t.forward(10)
t.up()
t.goto(300,250)
t.setheading(270)
t.down()
t.forward(10)
t.up()
t.goto(350,200)
t.setheading(180)
t.down()
t.forward(10)
t.up()
t.goto(250,200)
t.setheading(0)
t.down()
t.forward(10)
t.up()
t.goto(300,200)
t.down()
t.setheading(70)
t.forward(30)
t.up()
t.goto(300,200)
t.down()
t.setheading(0)
t.forward(30)


t.up()
t.speed(0)
t.color("silver")
t.goto(-300,-200)
t.setheading(180)
t.forward(470)
t.setheading(0)
t.down()
t.fillcolor("whitesmoke")
t.begin_fill()
t.forward(262)
t.setheading(90)
t.forward(500)
t.setheading(180)
t.forward(262)
t.setheading(262)
t.forward(500)
t.end_fill()



t.up()
t.color("gainsboro")
t.goto(-300,-200)
t.down()
t.fillcolor("gainsboro")
t.begin_fill()
t.setheading(190)
t.forward(200)
t.setheading(90)
t.forward(570)
t.setheading(350)
t.forward(200)
t.setheading(270)
t.forward(500)
t.end_fill()
t.up()
t.setheading(190)
t.forward(200)
t.color("gray")
t.down()
t.fillcolor("gray")
t.begin_fill()
t.forward(10)
t.setheading(90)
t.forward(571)
t.setheading(360)
t.forward(10)
t.setheading(270)
t.forward(571)
t.setheading(180)
t.forward(10)
t.end_fill()




t.up()
t.color("silver")
t.goto(400,-200)
t.setheading(0)
t.forward(400)
t.setheading(90)
t.down()
t.fillcolor("whitesmoke")
t.begin_fill()
t.forward(500)
t.setheading(180)
t.forward(200)
t.setheading(270)
t.forward(500)
t.setheading(0)
t.forward(200)
t.end_fill()


t.up()
t.color("gainsboro")
t.goto(400,-200)
t.down()
t.fillcolor("gainsboro")
t.begin_fill()
t.setheading(350)
t.forward(200)
t.setheading(90)
t.forward(570)
t.setheading(190)
t.forward(200)
t.setheading(270)
t.forward(500)
t.end_fill()
t.up()
t.setheading(350)
t.forward(200)
t.color("gray")
t.down()
t.fillcolor("gray")
t.begin_fill()
t.forward(10)
t.setheading(90)
t.forward(571)
t.setheading(180)
t.forward(10)
t.setheading(270)
t.forward(571)
t.setheading(0)
t.forward(10)
t.end_fill()




t.up()
t.color("gainsboro")
t.goto(-730,100)
t.down()
for i in range(2):
    t.fillcolor("gainsboro")
    t.begin_fill()
    t.forward(170)
    t.left(90)
    t.forward(100)
    t.left(90)
    t.end_fill()
t.up()
t.goto(-720,105)
t.down()
for i in range(2):
    t.fillcolor("gray")
    t.begin_fill()
    t.forward(30)
    t.left(90)
    t.forward(30)
    t.left(90)
    t.end_fill()
t.up()
t.goto(-680,105)
t.down()
for i in range(2):
    t.fillcolor("gray")
    t.begin_fill()
    t.forward(30)
    t.left(90)
    t.forward(60)
    t.left(90)
    t.end_fill()
t.up()
t.goto(-640,105)
t.down()
for i in range(2):
    t.fillcolor("gray")
    t.begin_fill()
    t.forward(30)
    t.left(90)
    t.forward(40)
    t.left(90)
    t.end_fill()
t.up()
t.goto(-600,105)
t.down()
for i in range(2):
    t.fillcolor("gray")
    t.begin_fill()
    t.forward(30)
    t.left(90)
    t.forward(20)
    t.left(90)
    t.end_fill()
t.up()
t.goto(-645,220)
t.color("gray")
t.down()
t.setheading(225)
t.forward(26.5)
t.up()
t.goto(-645,220)
t.color("gray")
t.down()
t.setheading(315)
t.forward(25)




t.up()
t.color("darkgray")
t.goto(445,150)
t.down()
t.fillcolor("darkgray")
t.begin_fill()
t.setheading(4)
t.forward(100)
t.setheading(90)
t.forward(105)
t.setheading(187)
t.forward(100)
t.setheading(270)
t.forward(100)    
t.end_fill()  
t.up()
t.goto(455,160)
t.color("dimgray")
t.setheading(0)
t.down()
t.fillcolor("dimgray")
t.begin_fill()
t.setheading(4)
t.forward(20)
t.setheading(90)
t.forward(40)
t.setheading(187)
t.forward(20)
t.setheading(270)
t.forward(40)    
t.end_fill()  
t.up()
t.goto(485,162)
t.color("dimgray")
t.setheading(0)
t.down()
t.fillcolor("dimgray")
t.begin_fill()
t.setheading(4)
t.forward(20)
t.setheading(90)
t.forward(60)
t.setheading(187)
t.forward(20)
t.setheading(270)
t.forward(60)    
t.end_fill()  
t.up()
t.goto(515,164)
t.color("dimgray")
t.setheading(0)
t.down()
t.fillcolor("dimgray")
t.begin_fill()
t.setheading(4)
t.forward(20)
t.setheading(90)
t.forward(80)
t.setheading(187)
t.forward(20)
t.setheading(270)
t.forward(80)    
t.end_fill()
t.up()
t.goto(490,270)
t.color("dimgray")
t.down()
t.setheading(225)
t.forward(23)
t.up()
t.goto(490,270)
t.color("dimgray")
t.down()
t.setheading(315)
t.forward(19)


t.up()
t.color("whitesmoke")
t.goto(-470,-245)
t.down()
t.setheading(90)
for i in range(2):
    t.fillcolor("whitesmoke")
    t.begin_fill()
    t.forward(250)
    t.right(90)
    t.forward(80)
    t.right(90)
    t.end_fill()
t.color("gray")
t.setheading(145)
t.fillcolor("gray")
t.begin_fill()
t.forward(20)
t.setheading(90)
t.forward(239)
t.setheading(0)
t.forward(16)
t.setheading(270)
t.forward(250)
t.end_fill()
t.up()
t.pensize(5)
t.color("gray")
t.goto(-470,-165)
t.down()
t.setheading(0)
t.forward(80)
t.up()
t.pensize(5)
t.color("gray")
t.goto(-470,-75)
t.down()
t.setheading(0)
t.forward(80)
t.up()
t.pensize(1)
t.color("white")
t.goto(-455,-205)
t.down()
for i in range(2):
    t.fillcolor("white")
    t.begin_fill()
    t.forward(50)
    t.left(90)
    t.forward(20)
    t.left(90)
    t.end_fill()
t.up()
t.pensize(5)
t.color("gray")
t.goto(-455,-225)
t.down()
t.forward(50)
t.up()
t.pensize(1)
t.color("gray")
t.goto(-450,-195)
t.down()
t.forward(40)
t.up()
t.pensize(1)
t.color("white")
t.goto(-455,-120)
t.down()
for i in range(2):
    t.fillcolor("white")
    t.begin_fill()
    t.forward(50)
    t.left(90)
    t.forward(20)
    t.left(90)
    t.end_fill()
t.up()
t.pensize(5)
t.color("gray")
t.goto(-455,-140)
t.down()
t.forward(50)
t.up()
t.pensize(1)
t.color("gray")
t.goto(-450,-110)
t.down()
t.forward(40)
t.up()
t.pensize(1)
t.color("white")
t.goto(-455,-35)
t.down()
for i in range(2):
    t.fillcolor("white")
    t.begin_fill()
    t.forward(50)
    t.left(90)
    t.forward(20)
    t.left(90)
    t.end_fill()
t.up()
t.pensize(5)
t.color("gray")
t.goto(-455,-55)
t.down()
t.forward(50)
t.up()
t.pensize(1)
t.color("gray")
t.goto(-450,-25)
t.down()
t.forward(40)

t.up()
t.pensize(2)
t.color("gray")
t.goto(-440,6)
t.down()
t.fillcolor("gray")
t.begin_fill()
t.forward(20)
t.setheading(80)
t.forward(40)
t.setheading(180)
t.forward(40)
t.setheading(280)
t.forward(40)
t.setheading(0)
t.forward(20)
t.end_fill()
t.up()
t.pensize(3)
t.color("dimgray")
t.goto(-435,46)
t.down()
t.setheading(90)
t.forward(20)
t.setheading(80)
t.forward(20)
t.up()
t.goto(-435,70)
t.setheading(300)
t.down()
t.fillcolor("dimgray")
t.begin_fill()
t.circle(30,70)
t.left(110)
t.circle(30,70)
t.end_fill()



t.up()
t.color("whitesmoke")
t.goto(560,-250)
t.down()
t.setheading(180)
for i in range(2):
    t.fillcolor("whitesmoke")
    t.begin_fill()
    t.forward(80)
    t.right(90)
    t.forward(180)
    t.right(90)
    t.end_fill()
t.color("gray")
t.fillcolor("gray")
t.begin_fill()
t.setheading(45)
t.forward(22)
t.setheading(90)
t.forward(165)
t.setheading(180)
t.forward(16)
t.setheading(270)
t.forward(180)
t.end_fill()

t.up()
t.goto(545,-190)
t.down()
t.setheading(180)
for i in range(4):
    t.forward(50)
    t.right(90)
t.up()
t.goto(525,-130)
t.down()
for i in range(2):
    t.fillcolor("gray")
    t.begin_fill()
    t.forward(10)
    t.right(90)
    t.forward(30)
    t.right(90)
    t.end_fill()
t.pensize(4)

def ro_rec(c_x,c_y,w,h,cs):
    t.up()
    t.goto(c_x-w/2+cs,c_y-h/2)
    t.down()
    for i in range(2):
        t.fillcolor("blue")
        t.begin_fill()
        t.fd(w-2*cs)
        t.circle(cs,90)
        t.fd(h-2*cs)
        t.circle(cs,90)
        t.end_fill()
ro_rec(580,111,80,120,10)
t.hideturtle()


import turtle
go=turtle.Turtle()
win=turtle.Screen()
go.hideturtle()

#code for G-----------
go.speed(0)
go.penup()
go.goto(-330,-34)
go.setheading(120)
go.pendown()
go.color("blue")
go.fillcolor("blue")
go.begin_fill()
go.setheading(120)
go.circle(60,180)
go.forward(80)
go.setheading(300)
go.circle(60,180)
go.setheading(30)
go.forward(23)
go.setheading(120)
go.forward(20)
go.setheading(210)
go.forward(65)
go.setheading(300)
go.forward(20)
go.setheading(30)
go.forward(23)
go.setheading(300)
go.circle(-39,180)
go.forward(80)
go.circle(-39,180)
go.setheading(30)
go.forward(20)
go.end_fill()

#-----O-----------
go.penup()
go.color("red")
go.goto(-130,-60)
go.setheading(100)
go.pendown()
go.fillcolor("red")
go.begin_fill()
go.setheading(100)
go.circle(60,180)
go.setheading(280)
go.forward(40)
go.circle(60,180)
go.forward(40)
go.end_fill()
go.penup()
go.goto(-155,-60)
go.setheading(100)
go.pendown()
go.fillcolor("grey")
go.begin_fill()
go.setheading(100)
go.circle(34,180)
go.setheading(280)
go.forward(45)
go.circle(34,180)
go.forward(45)
go.end_fill()
#----------o-----
go.speed(0)
go.penup()
go.goto(60,-60)
go.setheading(70)
go.pendown()
go.fillcolor("yellow")
go.begin_fill()
go.color("yellow")
go.setheading(80)
go.circle(60,180)
go.setheading(250)
go.forward(40)
go.circle(60,180)
go.forward(60)
go.end_fill()
go.penup()
go.goto(37,-60)
go.setheading(70)
go.pendown()
go.fillcolor("grey")
go.begin_fill()
go.setheading(80)
go.circle(35,180)
go.setheading(250)
go.forward(40)
go.circle(35,180)
go.forward(54)
go.end_fill()


#------------g---------
go.penup()
go.goto(250,100)
go.setheading(180)
go.pendown()
go.color("blue")
go.fillcolor("blue")
go.begin_fill()
go.forward(70)
go.circle(50,90)
go.forward(20)
go.circle(50,90)
go.forward(20)
go.circle(50,90)
go.forward(40)
go.setheading(0)
go.forward(30)
go.setheading(90)
go.forward(30)
go.setheading(180)
go.forward(30)
go.end_fill()
go.penup()
go.goto(195,70)
go.pendown()
go.fillcolor("grey")
go.begin_fill()
go.forward(5)
go.circle(30,90)
go.forward(5)
go.circle(30,90)
go.forward(5)
go.circle(30,90)
go.forward(5)
go.circle(30,90)
go.end_fill()

go.penup()
go.goto(180,-20)
go.pendown()
go.fillcolor("blue")
go.begin_fill()
go.setheading(260)
go.forward(20)
go.setheading(170)
go.forward(30)
go.circle(50,90)
go.forward(20)
go.circle(50,90)
go.forward(40)
go.circle(50,90)
go.forward(20)
go.circle(50,90)
go.forward(5)
go.setheading(80)
go.forward(20)
go.end_fill()

go.penup()
go.goto(190,-70)
go.pendown()
go.fillcolor("grey")
go.begin_fill()
go.setheading(170)
go.forward(40)
go.circle(25,90)
go.forward(20)
go.circle(20,90)
go.forward(40)
go.circle(20,90)
go.forward(25)
go.circle(20,90)
go.forward(40)
go.end_fill()



#-----l------------
go.penup()
go.goto(280,-150)
go.pendown()
go.color("green")
go.fillcolor("green")
go.begin_fill()
go.setheading(85)
go.forward(180)
go.setheading(355)
go.forward(30)
go.setheading(265)
go.forward(180)
go.setheading(175)
go.forward(30)
go.end_fill()

#----e--------
go.penup()
go.goto(440,-150)
go.pendown()
go.color("red")
go.fillcolor("red")
go.begin_fill()
go.setheading(350)
go.forward(25)
go.setheading(80)
go.forward(25)
go.circle(40,180)
go.forward(30)
go.circle(40,180)
go.setheading(170)
go.forward(25)
go.setheading(260)
go.circle(-15,180)
go.forward(6)
go.setheading(350)
go.forward(30)
go.end_fill()

go.penup()
go.goto(445,-138)
go.pendown()
go.fillcolor("white")
go.begin_fill()
go.setheading(80)
go.forward(12)
go.circle(16,180)
go.forward(12)
go.setheading(350)
go.forward(30)
go.end_fill()






#----------table-------
go.penup()
go.goto(-250,-146)
go.setheading(0)
go.pendown()
go.color("white")
go.fillcolor("white")
go.begin_fill()
go.forward(580)
go.setheading(315)
go.forward(50)
go.setheading(180)
go.forward(640)
go.setheading(53)
go.forward(45)
go.end_fill()

go.penup()
go.goto(-274,-180)
go.setheading(270)
go.pendown()
go.color("black")
go.fillcolor("black")
go.begin_fill()
go.forward(20)
go.setheading(0)
go.forward(639)
go.setheading(90)
go.forward(20)
go.setheading(180)
go.forward(639)
go.end_fill()
#------table legs---------
go.penup()
go.goto(-268,-200)
go.setheading(270)
go.pendown()
go.color("black")
go.pensize("4")
go.forward(25)
go.penup()
go.goto(-258,-200)
go.setheading(270)
go.pendown()
go.pensize("2")
go.forward(15)
go.penup()
go.goto(360,-200)
go.setheading(270)
go.pendown()
go.forward(25)
go.penup()
go.goto(350,-200)
go.setheading(270)
go.pendown()
go.pensize("2")
go.forward(15)

#----------chair2-----------
go.penup()
go.goto(380,-196)
go.pendown()
go.pensize(7)
go.color("black")
go.setheading(0)
go.forward(90)
go.pensize(5)
go.setheading(80)
go.forward(80)

go.penup()
go.goto(380,-196)
go.pendown()
go.pensize(2)
go.setheading(270)
go.forward(25)


go.penup()
go.goto(470,-196)
go.pendown()
go.setheading(270)
go.forward(25)

go.penup()
go.goto(390,-196)
go.pendown()
go.setheading(270)
go.forward(15)

go.penup()
go.goto(460,-196)
go.pendown()
go.setheading(270)
go.forward(15)


#-------chair------
go.penup()
go.goto(-300,-196)
go.pendown()
go.pensize(7)
go.color("black")
go.setheading(180)
go.forward(70)
go.pensize(5)
go.setheading(135)
go.forward(80)
go.penup()
go.goto(-370,-196)
go.pendown()
go.pensize(2)
go.setheading(270)
go.forward(25)
go.penup()
go.goto(-300,-196)
go.pendown()
go.setheading(270)
go.forward(25)
go.penup()
go.goto(-305,-196)
go.pendown()
go.setheading(270)
go.forward(15)
go.penup()
go.goto(-365,-196)
go.pendown()
go.setheading(270)
go.forward(15)

#-----------hands--------
go.penup()
go.goto(40,-100)
go.pendown()
go.color("yellow")
go.pensize(3)
go.setheading(300)
go.forward(20)
go.circle(-20,90)
go.penup()
go.goto(-70,-90)
go.pendown()
go.pensize(3)
go.setheading(200)
go.forward(20)
go.circle(20,90)

go.penup()
go.goto(-130,-100)
go.pendown()
go.color("red")
go.pensize(3)
go.setheading(300)
go.forward(20)
go.circle(-20,90)
go.penup()

go.penup()
go.goto(-240,-90)
go.pendown()
go.pensize(3)
go.setheading(200)
go.forward(20)
go.circle(-20,90)



while True:
    mus = turtle.Turtle()
    mus.pensize(10)
    mus.speed(0)
    mus.hideturtle()
    mus.color("black")  
    mus.setheading(180)
    mus.penup()
    mus.forward(240)
    mus.begin_fill()
    mus.fillcolor("white")
    mus.setheading(90)
    mus.forward(100)
    mus.pendown()
   
   

    mus.forward(150)
    mus.setheading(360)
    mus.forward(400)
    mus.setheading(270)
    mus.forward(150)
    mus.setheading(180)
    mus.forward(400)
    mus.end_fill()


    mus.pensize(5)
    mus.color("dark grey")
    mus.penup()
    mus.setheading(360)
    mus.forward(30)
    mus.setheading(90)
    mus.forward(30)
    mus.pendown()

    mus.forward(100)
    mus.left(135)
    mus.forward(10)
    mus.setheading(360)
    mus.penup()
    mus.forward(15)
    mus.left(135)
    mus.pendown()
    mus.forward(10)
    mus.setheading(270)
    mus.penup()
    mus.forward(100)
    mus.setheading(360)
    mus.pendown()
    mus.forward(350)
    mus.left(135)
    mus.forward(10)
    mus.penup()
    mus.setheading(270)
    mus.forward(15)
    mus.left(135)
    mus.pendown()
    mus.forward(10)
    mus.setheading(180)
    mus.penup()
    mus.forward(20)
    mus.pendown()


    mus.pensize(1)
    for i in range(16):
        mus.setheading(90)
        mus.forward(8)
        mus.backward(8)
        mus.setheading(180)
        mus.forward(20)
    mus.forward(12)
    mus.setheading(90)
    mus.forward(20)
    for i in range(4):
        mus.setheading(360)
        mus.forward(8)
        mus.backward(8)
        mus.setheading(90)
        mus.forward(20)

   
    mus.color("red","red")
    mus.pensize(3)
    mus.penup()
    mus.setheading(270)
    mus.forward(15)
    mus.setheading(360)
    mus.forward(15)
    mus.pendown()
    mus.right(45)
    mus.forward(50)
    mus.setheading(360)
    mus.left(30)
    mus.forward(50)
    mus.setheading(360)
    mus.right(30)
    mus.forward(100)
    mus.setheading(360)
    mus.left(45)
    mus.forward(100)
    mus.setheading(360)
    mus.right(60)
    mus.forward(80)
    mus.shape("triangle")
    mus.stamp()

    mus.setheading(180)
    mus.color("yellow","yellow")
    mus.penup()
    mus.forward(280)
    mus.pendown()
    mus.setheading(360)
    mus.left(45)
    mus.forward(70)
    mus.setheading(360)
    mus.right(30)
    mus.forward(50)
    mus.setheading(360)
    mus.left(15)
    mus.forward(100)
    mus.setheading(360)
    mus.right(4)
    mus.forward(150)
    mus.shape("triangle")
    mus.stamp()
    mus.penup()

    # run boss gif
    gif_turtle = turtle.Turtle()
    gif_turtle.penup()
    gif_turtle.hideturtle()
    gif_turtle.goto(-600, -300)
    play = 'bb.gif'
    turtle.register_shape(play)
    gif_turtle.speed(1)
    gif_turtle.shape(play)
    gif_turtle.showturtle()
    gif_turtle.forward(1450)
    gif_turtle.penup()

    mus.setpos(0,0)
    mus.pendown()
    mus.pensize(10)
    mus.pencolor("black")
    mus.speed(0)
    mus.setheading(180)
    mus.penup()
    mus.forward(240)
    mus.begin_fill()
    mus.fillcolor("green")
    mus.setheading(90)
    mus.forward(100)
    mus.pendown()

    time.sleep(0.5)
    mus.forward(150)
    mus.setheading(360)
    mus.forward(400)
    mus.setheading(270)
    mus.forward(150)
    mus.setheading(180)
    mus.forward(400)
    mus.end_fill()
    mus.pencolor("white")
    mus.pensize(2)
    mus.penup()
    mus.setheading(360)
    mus.forward(220)
    mus.setheading(90)
    mus.left(30)
    mus.pendown()
    mus.forward(170)
    mus.setheading(270)
    mus.right(3)
    mus.penup()
    mus.forward(70)
    mus.pendown()
    mus.circle(43)
    mus1 = turtle.Turtle()
    mus1.pencolor("blue")
    mus1.hideturtle()
    mus1.penup()
    mus1.setheading(180)
    mus1.forward(120)
    mus1.setheading(90)
    mus1.forward(150)
    mus1.pendown()
    mus1.pensize(10)
    mus1.forward(20)
   
    mus2 = turtle.Turtle()
    mus2.pencolor("blue")
    mus2.pensize(10)
    mus2.hideturtle()
    mus2.penup()
    mus2.setheading(180)
    mus2.forward(80)
    mus2.setheading(90)
    mus2.forward(200)
    mus2.pendown()
    mus2.forward(20)
    mus2.penup()
    mus2.setheading(180)
    mus2.forward(40)
    mus2.setheading(270)
    mus2.pendown()
    mus2.forward(20)
   
   
    for i in range(3):
        mus.setheading(360)
        mus.color("yellow")
        mus.shape("circle")
        mus.shapesize(0.5,.5)
        mus.speed(1)
        mus.showturtle()
        mus.penup()
        mus.forward(30)
        mus.setheading(90)
        mus.left(5)
        mus.forward(25)
        mus.setheading(90)
        mus.left(45)
        mus.pendown()
        mus.penup()    
        mus.circle(20,180,5)
        mus.pendown()
        mus.hideturtle()
    turtle.speed(0)
    turtle.penup()
    turtle.hideturtle()
    turtle.goto(0,0)
    turtle.pendown()
        




       

#goo----------------
        
















    
